/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion.Mantenimientos.Cliente;

import CapaLogica.cCliente;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joha
 */
public class iDeshabilitarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form iDeshabilitarCliente
     */
    cCliente oCliente ;
    int mensaje = 0;// 0 - error
    public iDeshabilitarCliente() {
        initComponents();
        oCliente= new cCliente();
        CargarDatosTabla(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBuscarBoleta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBoleta = new javax.swing.JTable();

        jLabel1.setText("DESHABILITAR CLIENTE");

        tbBoleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Cliente", "DNI", "Nombre Completo", "Habilitar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbBoleta);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlBuscarBoletaLayout = new javax.swing.GroupLayout(pnlBuscarBoleta);
        pnlBuscarBoleta.setLayout(pnlBuscarBoletaLayout);
        pnlBuscarBoletaLayout.setHorizontalGroup(
            pnlBuscarBoletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBuscarBoletaLayout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBuscarBoletaLayout.setVerticalGroup(
            pnlBuscarBoletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarBoletaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBuscarBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBuscarBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBuscarBoleta;
    private javax.swing.JTable tbBoleta;
    // End of variables declaration//GEN-END:variables

    private void CargarDatosTabla(ResultSet dato) {
        try{
            Object datos[][];
            String titulos[];
            DefaultTableModel dtmEjemplo;
            titulos= oCliente.getTitulos();
            if(dato!= null){
                datos = oCliente.getDatos(dato);// verificar por pato
            }
            else{
                datos = oCliente.getDatos();
            }
            if(datos.length==0){
                JOptionPane.showMessageDialog(null, "No hay clientes a mostrar.");
            }
            Object datos_filtrados[][]= new Object[datos.length][4];
            for(int i=0; i<datos.length;i++){
                for(int j=0; j<datos[0].length;i++){
                    if(titulos[j].toString().equals("IdCliente")){
                        datos_filtrados[i][0]= datos[i][j];
                    }
                    if(titulos[j].toString().equals("DNI")){
                        datos_filtrados[i][1]= datos[i][j];
                    }
                    if(titulos[j].toString().equals("Nombres")){
                        datos_filtrados[i][2]= datos[i][j] +" "+datos[i][j+1];
                    }
                    if(titulos[j].toString().equals("Estado")){
                        datos_filtrados[i][3]= datos[i][j];
                    }
                }
            }
            Object [] titu = new Object[4];
            titu[0]="IdCliente";
            titu[1]="DNI";
            titu[2]="Nombre Completo";
            titu[3]="Habilitado";
            dtmEjemplo = new DefaultTableModel(datos_filtrados, titu);
            tbBoleta.setModel(dtmEjemplo);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error:"+e);
        }
        
    }
}
